version: 2.0
jobs:
  build:
    working_directory: ~IPMJasperGoris
    docker:
      - image: circleci/openjdk
    steps:
      - checkout
      - run : mvn verify
      - store_test_results:
          path:  target/site
      - store_artifacts:
          path: target?
